cookbook/cookbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookbook/recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.user_create, name='register'),
    path('recipe/create', views.recipe_create, name='create_recipe'),
    path('account/', views.user_detail, name='user_detail'),
    path('account/edit', views.user_update, name='user_update'),
    path('<int:recipe_id>/edit', views.recipe_update, name='recipe_update'),
    path('home', views.home, name='home'),
    path('<int:recipe_id>/detail', views.recipe_detail, name='detail'),
    path('<int:recipe_id>/review', views.review, name='review'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('recipelisttest', views.recipe_list, name='testrecipe'),
]

cookbook/recipes/models.py
from django.db import models
from datetime import datetime as dt
from django.contrib.auth.models import User 
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
# OneToOne Link User Profile | For additional information on the default User Model.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatar', null=True)
    usertypes = (
        (True, 'Admin'),
        (False, 'User')
    )
    usertype = models.BooleanField(choices=usertypes, null=False, default=False)

    def __str__(self):
        return '{}'.format(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Category(models.Model):
    category = models.CharField(max_length=64, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.category)

# TimeField in forms: time_ = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='categories', null=True)
    date_added = models.DateTimeField(default=dt.now())
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    servings = models.IntegerField(validators=[MinValueValidator(0)], null=False, default=0)
    prep_time = models.DurationField()
    cook_time = models.DurationField()
    read_time = models.DurationField()
    picture = models.ImageField(upload_to='recipe_img', null=True)
    is_archived = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.name)

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='reviews')
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    comment = models.TextField(max_length=500)
    date_reviewed = models.DateTimeField(default=dt.now())
    
    def __str__(self):
        return 'User: {}, Recipe: {}'.format(self.user, self.recipe)

class Step(models.Model):
    # Step order will be determined by date added.
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='steps', null=False, blank=False)
    date_added = models.DateTimeField(default=dt.now())
    description = models.TextField()

    def __str__(self):
        return 'Recipe: {}, Step: {}'.format(self.recipe, self.description)

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients', null=False, blank=False)
    date_added = models.DateTimeField(default=dt.now())
    ingredient = models.TextField()

    def __str__(self):
        return '{}'.format(self.ingredient)
    

cookbook/recipes/forms.py
from django.forms import ModelForm
from .models import Recipe, Review, Profile, Ingredient, Step
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput

# What to fix:
# TimeField widget.
# - Instead of TextInput, use a more appropriate one.

class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {
            'password': PasswordInput()
        }

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['password', 'email', 'first_name', 'last_name']
        widgets = {
            'password': PasswordInput()
        }
    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        # fields = '__all__'
        exclude = ['added_by','date_added', 'is_archived']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        exclude = ['user', 'date_reviewed', 'recipe']

class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        exclude = ['date_added', 'recipe']

class StepForm(ModelForm):
    class Meta:
        model = Step
        exclude = ['date_added', 'recipe']

cookbook/recipes/views.py
from django.shortcuts import render, redirect
from .models import Category, Recipe, Review, Ingredient, Step, Profile
from .forms import RegistrationForm, UserForm, RecipeForm, ReviewForm, ProfileForm, IngredientForm, StepForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.models import modelformset_factory, inlineformset_factory
from django.forms import formset_factory
from django.db import IntegrityError, transaction

# Create your views here.
def index(request):
    # Index page.
    context = {}
    if request.user.is_authenticated:
        return redirect('recipes:home')
    else:
        return render(request, 'index.html', context)

@login_required
def home(request):
    # Home page. | Show trending, most popular, latest.
    context = {}
    context['latest_recipes'] = Recipe.objects.all().order_by('-id')[:4]
    context['latest_recipes1'] = Recipe.objects.all().order_by('-id')[5:9]
    context['latest_recipes2'] = Recipe.objects.all().order_by('-id')[10:14]
    return render(request, 'home.html', context)

@login_required
def recipe_create(request):
    # Add new recipe.
    context = {}
    context['recipe_form'] = RecipeForm()
    IngredientFormset = inlineformset_factory(Recipe, Ingredient, IngredientForm, extra=5)
    StepFormset = inlineformset_factory(Recipe, Step, StepForm, extra=5)
    context['ingredient_formset'] = IngredientFormset
    context['step_formset'] = StepFormset
    
    if request.method == 'POST':
        rec_form = RecipeForm(request.POST, request.FILES)
        if rec_form.is_valid():
            x = rec_form.save(commit=False)
            x.picture = request.FILES['picture']
            x.added_by = User.objects.get(username=request.user)
            x.save()

            ing_formset = IngredientFormset(request.POST, instance=x)
            stp_formset = StepFormset(request.POST, instance=x)
            if ing_formset.is_valid() and stp_formset.is_valid():
                ing_formset.save()
                stp_formset.save()
            
            return redirect('recipes:detail', recipe_id=x.id)
    
        ing_formset = IngredientFormset()
        stp_formset = StepFormset()
    
    return render(request, 'edit_recipe.html', context)


def save_ingredient():
    pass

def save_steps():
    pass

@login_required
def recipe_list(request): #category_id
    # use paginator here.
    # from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

    # context = {}
    # context['latest_recipes'] = Recipe.objects.all()
    # return render(request, 'recipelisttest.html', context)

    recipe_list = Recipe.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(recipe_list, 4)
    try:
        recipes = paginator.page(page)
    except PageNotAnInteger:
        recipes = paginator.page(1)
    except EmptyPage:
        recipes = paginator.page(paginator.num_pages)
    return render(request, 'recipelisttest.html', {'latest_recipes': recipes})

    pass

@login_required
def recipe_detail(request, recipe_id):
    # Recipe details
    context = {}
    context['recipe'] = Recipe.objects.get(id=recipe_id)
    context['reviews'] = Review.objects.all().filter(~Q(user=request.user), recipe=recipe_id) # Show reviews except the current user's.
    try:
        context['my_review'] = Review.objects.get(user=request.user, recipe=recipe_id) # Show the review of the current user.
    except:
        context['my_review'] = False
    context['review'] = ReviewForm()    
    return render(request, 'detail.html', context)

# @login_required
# def recipe_update(request, recipe_id):
#     # Update details.
#     context = {}
#     recipe = Recipe.object.get(id=recipe_id)
    
#     context['recipe'] = recipe
#     if request.method == 'POST':
#         form = RecipeForm(request.POST, instance=recipe)
#         if form.is_valid():
#             form.save()
#             return HttpResponse('Successfully updated.')
#         else:
#             context['form'] = form
#             return render(request, 'test.html', context)
#     else:
#         context['form'] = RecipeForm(instance=recipe)
#         return render(request, 'test.html', context)

@login_required
def recipe_update(request, recipe_id):
    context = {}
    recipe = Recipe.objects.get(id=recipe_id)
    IngredientFormset = inlineformset_factory(Recipe, Ingredient, IngredientForm, extra=2)
    StepFormset = inlineformset_factory(Recipe, Step, StepForm, extra=2)
    context['ingredient_formset'] = IngredientFormset
    context['step_formset'] = StepFormset

    if request.method == 'POST':
        rec_form = RecipeForm(request.POST, request.FILES)
        if rec_form.is_valid():
            x = rec_form.save(commit=False)
            x.picture = request.FILES['picture']
            x.added_by = User.objects.get(username=request.user)
            x.save()

            ing_formset = IngredientFormset(request.POST, instance=x)
            stp_formset = StepFormset(request.POST, instance=x)
            if ing_formset.is_valid() and stp_formset.is_valid():
                ing_formset.save()
                stp_formset.save()
            
            return redirect('recipes:detail', recipe_id=x.id)
    
        ing_formset = IngredientFormset()
        stp_formset = StepFormset()
    
    return render(request, 'create_recipe.html', context)

@login_required
def recipe_delete(request, recipe_id):
    # Only set status to 0.
    context = {}
    pass

@login_required
def review(request, recipe_id):
    # With rating and comment.
    context = {}
    context['recipe_id'] = recipe_id
    recipe = Recipe.objects.get(id=recipe_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            x = form.save(commit=False)
            x.recipe_id = recipe_id
            x.user = User.objects.get(username=request.user)
            x.save()
            return redirect('recipes:detail', recipe_id)
        else:
            return redirect('recipes:detail', recipe_id)
    else:
        return redirect('recipes:detail', recipe_id)

def user_create(request):
    # Register user.
    form = RegistrationForm()
    context = {}
    if request.user.is_authenticated:
        return redirect('recipes:home')
    
    context['form'] = form
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(request.POST['password'])
            user.save()
            login(request, user)
            return redirect('recipes:home')
        else:
            context['form'] = form
            return redirect('recipes:index')
    return render(request, 'registration.html', context)

@login_required
def user_profile(request):
    context = {}
    context['form'] = ProfileForm()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.avatar = request.FILES['avatar']
            user.save()
            # Change redirected site.
            return redirect('recipes:home')
        else:
            context['form'] = form
            # Change
            return render(request, 'home.html', context)
    else:
        return render(request, 'home.html', context)

@login_required
def user_detail(request):
    # Userinfo.
    context = {}
    context['profile'] = Profile.objects.get(user=request.user)

    context['my_recipes'] = Recipe.objects.all().filter(added_by=request.user)
    return render(request, 'account.html', context)

@login_required
def user_update(request):
    context = {}
    context['user_form'] = UserForm(instance=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            login(request, request.user)
            return redirect('recipes:user_detail')
        else:
            context['user_form'] = user_form
            return render(request, 'account_edit.html', context)
    else:
        context['form'] = UserForm(instance=request.user)
        return render(request, 'account_edit.html', context)

def user_login(request):
    # Login credentials.
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            print(user)
            login(request, user)
            return redirect('recipes:index')
        else:
            print('User not found.')
            
    return render(request, 'login.html', context)

def user_logout(request):
    context = {}
    logout(request)
    return redirect('recipes:index')

def save_step(request):
    context = {}
    StepFormset = modelformset_factory(Step, StepForm)
    formset = StepFormset()
    context['step_formset'] = formset
    return render(request, 'test.html', context)

cookbook/recipes/templates/aboutme.html
{% extends 'base.html' %}

{% block head %}
    Account page.
{% endblock %}

{% block body %}

{% endblock %}

cookbook/recipes/templates/account.html
{% extends 'base-2.html' %}
{% load static %}

{% block title %}
    Ricetta | My Account
{% endblock %}

{% block body %}

    <!-- Show User Profile -->
    <!-- Show recipes created -->
    <!-- Create button which will redirect to recipe creation page -->
    <!-- Edit profile info button -->

        <div class="row nav-padding-acct account-main-div">
            <div class="col-md-2 vertical-rule-right-nocolor account-details-div">
                <!-- Make it clickable -->
                {% if profile.avatar %}
                    <img class="avatar" src="{{ profile.avatar.url }}" alt="profile_img"> <br />
                {% else %}
                    <img class="avatar" src="{% static 'icon/Profile Icon.png' %}" alt="profile_img"> <br />
                {% endif %}
                <h5 class="ricetta-h5 font-roboto-bold ricetta-font-color">{{ request.user }}<h5>
                <a href="{% url 'recipes:user_update' %}" class="a-des"><button type="submit" class="ricetta-button ricetta-button-comment">Edit Profile</button></a>
            </div>
            <div class="col">
                <div class="row py-5">
                    <div class="card-deck px-3">
                    <div class="card mx-5 border create-new-recipe">
                        <div class="create-new-recipe">
                            <a href="{% url 'recipes:create_recipe' %}" class="a-des">
                                <p class="font-roboto-thin create-new-recipe-plus">+</p>
                                <p class="font-roboto-thin create-new-recipe-text">Create a new recipe</p>
                            </a>
                        </div>
                    </div>
                    {% for recipe in my_recipes %}
                        <div class="card shadow-lg mx-5">
                            <a href="{% url 'recipes:detail' recipe.id %}" class="a-des">
                                {% if recipe.picture %}
                                    <img class="card-img-top" src="{{ recipe.picture.url }}" alt="Card image cap">
                                {% else %}
                                    <img class="card-img-top" src="{% static 'img/salad.jpg' %}" alt="Card image cap">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title mb-0">{{ recipe.name }}</h5>
                                    <p class="card-text mt-0"><small class="text-muted">by {{ recipe.added_by }}</small></p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>


{% endblock %}

cookbook/recipes/templates/account_edit.html
{% extends 'base-2.html' %}

{% block title %}
    Ricetta | Edit Account
{% endblock %}

{% block body %}
    
    <div class="row nav-padding-acct">
        <div class="col-md-2 vertical-rule-right-nocolor account-details-div">
                <!-- Make it clickable -->
                <img class="avatar" src='../static/icon/Profile Icon.png' alt="profile_img"> <br />
            <h5 class="ricetta-h5 font-roboto-bold ricetta-font-color"><h5>
            <a href="{% url 'recipes:user_update' %}" class="a-des"><button type="submit" class="ricetta-button ricetta-button-comment">Edit Profile</button></a>
        </div>
        <div class="col-md-10">
            <form action="{% url 'recipes:user_update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="row">
                    <div class="col-md-4" style="text-align:right">
                        <p class="font-roboto-regular ricetta-font-color font-edit-acct">First Name:<p>
                    </div>
                    <div class="col-md-8" style="text-align:left">
                        <input class="textbox-edit" type="text" name="first_name" value="Admin" maxlength="30" id="id_first_name">
                    </div>

                    <div class="col-md-4" style="text-align:right">
                        <p class="font-roboto-regular ricetta-font-color font-edit-acct">Last Name:<p>
                    </div>
                    <div class="col-md-8" style="text-align:left">
                        <input class="textbox-edit" type="text" name="last_name" value="Minad" maxlength="150" id="id_last_name">
                    </div>

                    <div class="col-md-4" style="text-align:right">
                        <p class="font-roboto-regular ricetta-font-color font-edit-acct">Email Address:<p>
                    </div>
                    <div class="col-md-8" style="text-align:left">
                        <input class="textbox-edit" type="email" name="email" value="admin@admin.com" maxlength="254" id="id_email">
                    </div>

                    <div class="col-md-4" style="text-align:right">
                        <p class="font-roboto-regular ricetta-font-color font-edit-acct">Password:<p>
                    </div>
                    <div class="col-md-8" style="text-align:left">
                        <input class="textbox-edit" type="password" name="password" maxlength="128" required="" id="id_password">
                    </div>
                </div>
                <div class="ricetta-edit-button-div">
                    <input class="ricetta-edit-button" type="submit" value="Save changes">
                </div>

            </form>     
        </div>   
    </div>

{% endblock %}

cookbook/recipes/templates/detail.html
{% extends 'base-2.html' %}

{% block title %}
    Ricetta | Recipes > {{ recipe.category }} > {{ recipe.name }}
{% endblock %}

{% block body %}

    <div class="nav-padding">

        <div class="container-fluid clean-carousel" style="height: 90%;">
            <div class="row" style="height: 100%;">
                <div class="col-sm-4">
                    <div class="ricetta-detail-header">
                        <h2 class="ricetta-detail-title font-roboto-bold"> {{ recipe.name }} </h2>
                        <h5 class="font-slabo ricetta-font-color ricetta-item-margin"> By {{ recipe.added_by }} </h5>
                        <p class="font-slabo ricetta-font-color ricetta-item-margin"> "{{ recipe.description }}" </p>

                        <div class="ricetta-card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-5 vertical-rule-right">
                                        <p class="font-roboto-medium ricetta-font-color">Prep: {{ recipe.prep_time }} </p>
                                        <p class="font-roboto-medium ricetta-font-color">Cook: {{ recipe.cook_time }}</p>
                                        <p class="font-roboto-medium ricetta-font-color">Ready: {{ recipe.read_time }}</p>
                                    </div>
                                    <div class="col-sm-6 ricetta-font-color">
                                        <div>
                                            <p>Reviews</p>
                                            <p>Stars</p>
                                        </div>
                                        <hr class="ricetta-hr ricetta-detail-hr">
                                        <div class="row">
                                            <img class="portion-icon" src="../static/icon/Portion Icon.png" alt="Serving Size: ">
                                            <p class="font-roboto-thin ricetta-font-color serve-size-font">Serving Size: {{ recipe.servings }}</p>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-8">
                    <img class="ricetta-image-fit" src="{{ recipe.picture.url }}" alt="Recipe picture">
                </div>
            </div>
        </div>
        <div class="ricetta-detail-container" style="margin-top:50px">
            <div>
                <h2 class="header2-detail font-roboto-bold">INGREDIENTS</h2>
            </div>
            <hr class = "ricetta-hr ricetta-pages-hr">
            <div>
                {% if recipe.ingredients.all|length == 0 %}
                    <div class="col-md-5 empty-comments-div">
                        <p class="font-roboto-thin ricetta-light-font-color align-center">No steps have been added.</p>
                    </div>
                {% else %}
                    {% for ingredient in recipe.ingredients.all %}
                        <p class="ricetta-detail-font ricetta-font-color font-slabo"> {{ ingredient }} </p>
                    {% endfor %}
                {% endif %}
            </div>

        </div>

        <div class="ricetta-detail-container">
            <div>
                <h2 class="header2-detail font-roboto-bold">DIRECTIONS</h2>
            </div>
            <hr class = "ricetta-hr ricetta-pages-hr">
            <div>
                {% if recipe.steps.all|length == 0 %}
                    <div class="col-md-5 empty-comments-div">
                        <p class="font-roboto-thin ricetta-light-font-color align-center">No steps have been added.</p>
                    </div>
                {% else %}
                    <div class="row">
                        <ol>
                            {% for step in recipe.steps.all %}
                                <div class="col-sm-10">
                                    <li class="ricetta-detail-font ricetta-font-color font-slabo">{{ step.description }}</li>
                                </div>
                            {% endfor %}
                        </ol>
                    </div>


                    {% comment %}
                        
                        <ol>
                            {% for step in recipe.steps.all %}
                                <div class="col-sm-2">
                                <li></li>
                                </div>
                                <div class="col-sm-10">
                                <p>{{ step.description }}</p>
                                </div>
                            {% endfor %}
                        </ol>
                    </div>
                    
                    {% endcomment %}
                {% endif %}
            </div>

        </div>

        <!-- Comment Section -->
        <div class="container-fluid">
            <div class="ricetta-detail-container">
                <h2 class="header2-detail font-roboto-bold">LEAVE A COMMENT</h2>
            </div>
            <hr class = "ricetta-hr ricetta-pages-hr">
            {% if my_review %}
                <!-- Star rating -->
                Rating: {{ my_review.rating }} <br />
                Description: {{ my_review.comment }}
                Date Reviewed: {{ my_review.date_reviewed }}
                <!-- Edit button here, change output -->
            {% else %}
                <!-- Star rating -->
                <div class="ricetta-detail-container">
                    <form action="{% url 'recipes:review' recipe.id %}" method="POST">
                        {% csrf_token %}
                        <div>
                            <p class="font-roboto ricetta-font-color" style ="font-size:20px">Rate this recipe</p>

                            <div class="ricetta-rate-div">
                                <img src="../static/icon/Empty Star Icon.png" class="rate-icon">
                                <img src="../static/icon/Empty Star Icon.png" class="rate-icon">
                                <img src="../static/icon/Empty Star Icon.png" class="rate-icon">
                                <img src="../static/icon/Empty Star Icon.png" class="rate-icon">
                                <img src="../static/icon/Empty Star Icon.png" class="rate-icon">
                            </div>
                            {% comment %}
                            stars placeholder    
                            {% endcomment %}
                        </div>
                        <div>
                            <p class="font-roboto-regular ricetta-font-color" style ="font-size:20px">Comment</p>
                            <textarea class="ricetta-textbox-detail" name="comment" rows="5" columns"50"></textarea>
                        </div>
                        
                        <button type="submit" class="ricetta-button ricetta-button-comment">Comment</button>           
                    </form>
                </div>
            {% endif %}
            <div>
                
            
                            
            {% if reviews|length == 0 %}
                <div class="col-md-5 empty-comments-div">
                    <p class="font-roboto-thin ricetta-light-font-color align-center">Be the first to review this recipe!</p>
                </div>
            {% else %}
                {% for review in reviews.all %}
                    <div class="col-md-6 ricetta-detail-container comments-sec-div">
                        <div class="row">
                            <div class="col-sm-3" style="min-width:200px;">
                                <div>
                                    <img src="../static/icon/Star Icon.png" class="comment-rating-icon">
                                    <img src="../static/icon/Star Icon.png" class="comment-rating-icon">
                                    <img src="../static/icon/Star Icon.png" class="comment-rating-icon">
                                    <img src="../static/icon/Star Icon.png" class="comment-rating-icon">
                                    <img src="../static/icon/Empty Star Icon.png" class="comment-rating-icon">
                                    
                                </div>
                            </div>
                            <div class="col-sm-3" style="padding-left:0px;">
                                <p class="ricetta-font-color font-roboto ricetta-comments-sec-font"> {{ review.user }}</p>
                            
                            </div>
                            </br>
                            
                        </div>

                        <p class="ricetta-font-color font-roboto-light-italic ricetta-comment-date">{{ review.date_reviewed }}</p>
                        <p class="font-slabo ricetta-font-color ricetta-comments-font"> {{ review.comment }}</p>
                        <hr class="ricetta-hr ricetta-comment-hr">
                    </div>
                {% endfor %}
            {% endif %}


        </div>

    </div>


{% endblock %}

cookbook/recipes/templates/list.html
{% extends 'base.html' %}

{% block head %}
    List.
{% endblock %}

{% block body %}

{% endblock %}

cookbook/recipes/templates/test.html
{% extends 'base-2.html' %}

{% block title %}
    this is for testing the forms.
{% endblock %}

{% block body %}
    <!-- <form action="{% url 'recipes:create_recipe' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} <br />
            {{ field }} <br />
        {% endfor %}
        <input type="submit" value="Create">
    </form> -->

    {% for form in step_formset.forms %}
        <div class="link-formset">
            {{ form.description }}
        </div>
    {% endfor %}
    {{ step_formset.management_form }}
{% endblock %}